---

- hosts: node1
  gather_facts: true
  become: true


  vars:
    region: us-east-1
    key_name: sureshdevops
    image: ami-0557a15b87f6559cf

  tasks:
  - pip:
      name: boto
 # - include_vars: password.yml
  - name: Create a ec2 instance 
    ec2:
     # aws_access_key: "{{ec2_access_key}}"
     # aws_secret_key: "{{ec2_secret_key}}"
      key_name: "{{ key_name }}"
      region: "{{ region }}"
      instance_type: t2.micro
      image: "{{image}}"
      wait: true
      count: 1
  
  tags: create_ec2 
